# Generated by Django 5.2.17 on 2026-08-20 04:40

import community.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=community.models.media_upload_path, validators=[community.models.validate_media_file])),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], editable=False, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='community.post')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
