# Generated by Django 5.2.17 on 2026-08-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_postmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
